#!/bin/sh

if [ -d "autom4te.cache" ]; then rm -Rf $autom4te.cache; fi

autoreconf -fi

case `uname -s` in
    Darwin)
    export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"
    export LDFLAGS="-L/usr/local/opt/openssl/lib"
    export CPPFLAGS="-I/usr/local/opt/openssl/include"
    ;;
esac

./configure RANLIB="ranlib -no_warning_for_no_symbols"


