#!/bin/sh

autoreconf -fi

case `uname -s` in
    Darwin)
    FLAGS="$FLAGS --without-acls \
                  --disable-zeroconf \
                  --with-libevent-header=/usr/local/include \
                  --with-libevent-lib=/usr/local/lib \
                  --with-afpstats"
    ;;
esac

./configure $FLAGS "$@" CC=gcc-10

make clean
