#!/bin/zsh

# Startup daemon for Netatalk on macOS

# Root check
if [ "$(id -u)" != "0" ]; then
   printf "Error: The startup daemon for Netatalk needs to be executed with sudo privileges.\n" 1>&2
   exit 1
fi

# Prepare the environment
PREFIX=/usr/local/sbin
. /etc/rc.common
 
# The start subroutine
StartService() {
   #Ensure network availability before running daemon
    ConsoleMessage "Starting netatalk fileserver"
    $PREFIX/cnid_metad
    $PREFIX/afpd
}
 
# The stop subroutine
StopService() {
    ConsoleMessage "Stopping netatalk fileserver"
    killall -TERM afpd
    killall -TERM cnid_metad
}
 
# The restart subroutine
RestartService() {
    ConsoleMessage "Restarting netatalk fileserver"
    killall -HUP afpd
    killall -HUP cnid_metad
}
 
RunService "$1"
