name: netatalk

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, macOS, arm64]   
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash -l {0}"   
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: ./bootstrap
    - name: Run make
      run: make
    - name: Run check
      run: make check
    - name: Run distcheck
      run: make distcheck
